# Generated by Django 4.0.3 on 2022-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Applicant name')),
                ('address', models.CharField(max_length=400)),
                ('zip_code', models.CharField(max_length=300, verbose_name='Zip Code')),
                ('des', models.TextField(blank=True, verbose_name='About yourslf')),
                ('phone', models.IntegerField(verbose_name='Contact Phone')),
                ('web', models.URLField(blank=True, verbose_name='Web Address')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='male', max_length=6)),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
